app = "shop-node-js"
primary_region = "fra"
console_command = "/bin/bash"

[build]
  builder = "heroku/buildpacks:20"
 

[processes]
  app = "node app.js"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  MONGO_DEFAULT_DATABASE = "shop"
  AWS_BUCKET_REGION = "eu-north-1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256